"""changes in database

Revision ID: 016a03f2cb39
Revises: ec4b4d7b7cbf
Create Date: 2026-07-23 19:09:06.800336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '016a03f2cb39'
down_revision: Union[str, Sequence[str], None] = 'ec4b4d7b7cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('admin', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_at')
    op.drop_column('admin', 'phone_number')
    op.drop_column('admin', 'city')
    # ### end Alembic commands ###
