"""Changes in Order table

Revision ID: 33121050b644
Revises: 4099df74cd28
Create Date: 2026-07-30 18:35:25.376370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '33121050b644'
down_revision: Union[str, Sequence[str], None] = '4099df74cd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('orders', sa.Column('product_price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'paid')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'product_price')
    op.drop_column('orders', 'product_name')
    # ### end Alembic commands ###
