"""paid column add in orders table.

Revision ID: 3bfe1a479f0f
Revises: 560d99fc6a6f
Create Date: 2025-12-16 21:07:43.043342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfe1a479f0f'
down_revision: Union[str, Sequence[str], None] = '560d99fc6a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paid', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid')
    # ### end Alembic commands ###
