"""add new account_type column in Sellers table

Revision ID: 53a2a5cb650b
Revises: 9f8abf0fa70c
Create Date: 2025-12-01 14:48:15.299853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '53a2a5cb650b'
down_revision: Union[str, Sequence[str], None] = '9f8abf0fa70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'account_type')
    # ### end Alembic commands ###
