"""password column added in Admin

Revision ID: 53d793e0fc78
Revises: d237640cde12
Create Date: 2025-12-26 04:10:34.823385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '53d793e0fc78'
down_revision: Union[str, Sequence[str], None] = 'd237640cde12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sa.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=300),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
