"""new status column add in Cart table

Revision ID: 560d99fc6a6f
Revises: 64dcd72fce1a
Create Date: 2025-12-15 14:26:22.961112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '560d99fc6a6f'
down_revision: Union[str, Sequence[str], None] = '64dcd72fce1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'status')
    # ### end Alembic commands ###
