"""set max length 300 in Admin table in password column

Revision ID: 65a9517847d6
Revises: 9bdd045b580c
Create Date: 2025-12-18 19:18:14.175670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a9517847d6'
down_revision: Union[str, Sequence[str], None] = '9bdd045b580c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
