"""changes in product model

Revision ID: 80882b60867b
Revises: 016a03f2cb39
Create Date: 2026-07-26 18:07:36.310723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80882b60867b'
down_revision: Union[str, Sequence[str], None] = '016a03f2cb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('weight', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('products', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'weight')
    # ### end Alembic commands ###
