"""add new column create_at in Users column.

Revision ID: 90c0da87b1f5
Revises: 079f3f69cc6e
Create Date: 2025-12-10 17:47:57.853850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c0da87b1f5'
down_revision: Union[str, Sequence[str], None] = '079f3f69cc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###
