"""set max length 300 in Admin table in password column.

Revision ID: af5877c75af8
Revises: 65a9517847d6
Create Date: 2025-12-18 19:21:32.956948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'af5877c75af8'
down_revision: Union[str, Sequence[str], None] = '65a9517847d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sa.VARCHAR(length=25),
               type_=sqlmodel.sql.sqltypes.AutoString(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=250),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###
