"""make changes in database.py

Revision ID: d237640cde12
Revises: af5877c75af8
Create Date: 2025-12-22 07:57:20.566164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd237640cde12'
down_revision: Union[str, Sequence[str], None] = 'af5877c75af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('admin', 'password',
               existing_type=sa.VARCHAR(length=250),
               type_=sqlmodel.sql.sqltypes.AutoString(length=30),
               existing_nullable=False)
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('sellers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('sellers', 'age',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    op.drop_column('sellers', 'create_at')
    op.alter_column('users', 'age',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'age',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('sellers', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.alter_column('sellers', 'age',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('sellers', 'created_at')
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'created_at')
    op.alter_column('admin', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.drop_column('admin', 'created_at')
    # ### end Alembic commands ###
