"""colour column is nullable True in Products table.

Revision ID: ddd9c9692b90
Revises: 90c0da87b1f5
Create Date: 2025-12-10 19:44:48.876721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd9c9692b90'
down_revision: Union[str, Sequence[str], None] = '90c0da87b1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'colour',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'colour',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
