"""seller_id column create in carts table.

Revision ID: ec4b4d7b7cbf
Revises: 5e24fe307b9b
Create Date: 2026-01-01 10:38:58.011207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4b4d7b7cbf'
down_revision: Union[str, Sequence[str], None] = '5e24fe307b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cart', 'sellers', ['seller_id'], ['id'])
    op.alter_column('products', 'size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'seller_id')
    # ### end Alembic commands ###
