"""changes in admin column

Revision ID: fefbe7e5e7b4
Revises: 53d793e0fc78
Create Date: 2025-12-26 07:25:33.475425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fefbe7e5e7b4'
down_revision: Union[str, Sequence[str], None] = '53d793e0fc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sa.VARCHAR(length=300),
               type_=sqlmodel.sql.sqltypes.AutoString(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
